### ISSUE TITLE
Compatiblity issues between Oxipay and other "Payment Gateway" plugins

### ISSUE THREAD

**Issue by blueninja2** [oxipay/oxipay-woocommerce#36]
Erik at Buy Anime Aus ( https://www.buyanimeaus.com.au ) reported an issue between Oxipay and another payment gateway plugin installed on his site (WordPress/WooCommerce).

When they enable Oxipay, the other payment gateway becomes unusable - they get an error message as per the screenshot below:

But when they disable Oxipay, the other plugin works fine.

![image](https://cloud.githubusercontent.com/assets/22509613/23983683/61bb8136-0a65-11e7-95d5-b3ce019bf6d1.png)

**Comment by esteban-terem** [comment]
Both plugins (Oxipay and the another payment gateway plugin) are hooking a filter for `woocommerce_thankyou_order_id` and are both processing the order payment callback independently of which Payment Gateway processed the payment. In this case, Oxipay process it first. When the another plugin tries to process it, `wc_get_order( $order_id )` returns `false` and due to another bug handling _non-existent_ orders in the other plugin, that specific error is produced (calling `add_order_note()` on `boolean`)

**Comment by esteban-terem** [comment]
Fix PR: https://github.com/oxipay/oxipay-woocommerce/pull/41

**Comment by blueninja2** [comment]
Contacted Erik who installed the latest version of Afterpay and a version of the Oxipay plugin with the fix and he said that the issue is now resolved.
